# ██╗    ██╗ ██████╗ ██████╗ ██╗  ██╗     ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
# ██║    ██║██╔═══██╗██╔══██╗██║ ██╔╝    ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
# ██║ █╗ ██║██║   ██║██████╔╝█████╔╝     ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
# ██║███╗██║██║   ██║██╔══██╗██╔═██╗     ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
# ╚███╔███╔╝╚██████╔╝██║  ██║██║  ██╗    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#  ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 

# Work machine sessions

[[session]]
name = "home"
path = "~"

[[session]]
name = "tinkering"
path = "~"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "nvim"

[[session]]
name = "magento-cloud"
path = "~"
startup_command = "magento-cloud tunnel:open"

[[session]]
name = "magento-nodes-ssh (custom)"
path = "~"
startup_command = "magento-nodes"

[[session]]
name = "magento-main"
path = "/Users/marko.prodanovic/Sites/arcteryx/ax-magento"
startup_command = "nvim"

[[session]]
name = "arcteryx (monorepo)"
path = "/Users/marko.prodanovic/Sites/arcteryx"
startup_command = "nvim"

[[session]]
name = "nvim config"
path = "~/.config/nvim"
startup_command = "nvim"

[[session]]
name = "kiro config"
path = "~/.kiro/settings"
startup_command = "nvim"
