# ██████╗ ███████╗██████╗ ███████╗ ██████╗ ███╗   ██╗ █████╗ ██╗          ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
# ██╔══██╗██╔════╝██╔══██╗██╔════╝██╔═══██╗████╗  ██║██╔══██╗██║         ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
# ██████╔╝█████╗  ██████╔╝███████╗██║   ██║██╔██╗ ██║███████║██║         ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
# ██╔═══╝ ██╔══╝  ██╔══██╗╚════██║██║   ██║██║╚██╗██║██╔══██║██║         ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
# ██║     ███████╗██║  ██║███████║╚██████╔╝██║ ╚████║██║  ██║███████╗    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
# ╚═╝     ╚══════╝╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 

# Personal machine sessions

[[session]]
name = "home"
path = "~"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "nvim"

[[session]]
name = "nvim config"
path = "~/.config/nvim"
startup_command = "nvim"

[[session]]
name = "vek-moderne-arhitekture"
path = "~/Documents/Dev/vek-moderne-arhitekture"
startup_command = "bash ~/.config/sesh/scripts/vek-moderne-arhitekture.sh"

[[session]]
name = "op-tracker-frontend"
path = "~/Documents/Dev/op-tracker-frontend"
startup_command = "bash ~/.config/sesh/scripts/op-tracker-frontend.sh"

[[session]]
name = "morpheus"
path = "~"
startup_command = "ssh marko@morpheus"

[[session]]
name = "media-server"
path = "~"
startup_command = "ssh admin@marko-server.local"


